version: '3'

services:

  follow-api:
    container_name: follow-api
    depends_on:
      - follow_db
    ports:
      - 8081:8080
    image: ghcr.io/nico-werner/jibberjabber-followers-api:main
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: follow_db
      DB_PORT: 5437

  follow_db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
    volumes:
      - followdata:/var/lib/postgresql/data

  post-api:
    container_name: post-api
    depends_on:
      - db
    ports:
      - 8082:8080
    image: ghcr.io/nico-werner/jibberjabber-posts-api:main
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_db
      DB_PORT: 5433

  db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    depends_on:
      - keycloak-db
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
    command: start-dev

  keycloak-db:
    container_name: keycloak-db
    image: postgres:12
    ports:
      - 5436:5432
    environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
        POSTGRES_DB: keycloak
    volumes:
      - keycloakdata:/var/lib/postgresql/data


volumes:
  pgdata:
    external: true
  keycloakdata:
    external: true
  followdata:
    external: true